- name: Node Port Install
  hosts: nodeporter_host
  gather_facts: true 

  tasks:
  - name: Update
    shell: sudo apt-get update
  - name: Install prometheus-node-exporter
    shell: sudo apt-get install prometheus-node-exporter -y
  - name: Enable prometheus-node-exporter
    shell: sudo systemctl --now enable prometheus-node-exporter
  - name: Start prometheus-node-exporter
    shell: sudo systemctl --now start prometheus-node-exporter
