global:
  scrape_interval: 5s
  external_labels:
    cluster: kiwoom
    replica: 0
    tenant: team-kiwoom

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9093']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['127.0.0.1:19093']
  - job_name: 'minio'
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['127.0.0.1:9000']
  - job_name: 'querier'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'store_gateway'
    static_configs:
      - targets: ['127.0.0.1:19094']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.1.234:9100']
